model_name: "model_name_placeholder"
model_kwargs:
  thinking_budget: None
  system_prompt: 당신은 사용자의 질문에 친절하고 논리적으로 답변해 주는 법률 전문가 챗봇 입니다.

tasks: kcl_mcqa
tasks_kwargs:
  with_precedents: False

n_jobs: 8
verbose: False

hydra:
  run:
    dir: outputs_infer/${tasks}/${model_name}/${now:%Y-%m-%d_%H-%M-%S}